version: '3.2'
services:
  app:
    image: democraciaenred/participes-app:testing
    environment:
      APP_ENV: production
      APP_NAME: Participes
      APP_DEBUG: 'true'
      APP_URL: http://localhost
      CONTAINER_ROLE: app
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - public_dir:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - 9000:9000
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - type: volume
        source: public_dir
        target: /var/www/html
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/conf.d/app.conf
        target: /etc/nginx/conf.d/default.conf
    restart: unless-stopped

  queue:
    image: democraciaenred/participes-app:testing
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 31415926
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    restart: unless-stopped

volumes:
  public_dir:
  redis:
