version: '3.2'

services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: participes:latest
    container_name: participes-app
    working_dir: /var/www/html
    env_file:
      - ./docker/.env
    environment:
      CONTAINER_ROLE: app
    volumes:
      - composer_cache:/home/.laravel/.composer
      - public_dir:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - 9000:9000
    depends_on:
      - nginx
      - mysql
      - redis
    restart: unless-stopped
    networks:
      - participes
 

  queue:
    image: participes:latest
    container_name: participes-queue
    depends_on:
      - app
      - mysql
      - redis
      - nginx
    volumes:
      - public_dir:/var/www/html
      - composer_cache:/home/.laravel/.composer
    env_file:
      - ./docker/.env
    environment:
      CONTAINER_ROLE: queue
    networks:
      - participes
  # queue:
  #   image: democraciaenred/participes-app:testing
  #   build: .
  #   env_file:
  #     - ./docker/.env
  #   environment:
  #     CONTAINER_ROLE: queue
  #   depends_on:
  #     - 'app'
  #   volumes:
  #     - public_dir:/var/www/html
  #     - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  #     - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
  #   networks:
  #     - participes

  nginx:
    image: nginx:alpine
    container_name: participes-nginx
    ports:
      - "8000:80"
      # - "443:443"
    volumes:
      - type: volume
        source: public_dir
        target: /var/www/html
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
      # - type: bind
      #   source: ./docker/nginx/conf.d/nginx.conf
      #   target: /etc/nginx/conf.d/nginx.conf
    restart: unless-stopped
    networks:
      - participes

  redis:
    image: redis
    container_name: participes-redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - participes

  mysql:
    image: mysql:5.7
    container_name: participes-mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 31415926
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql:/var/lib/mysql
    ports: 
      - 3306:3306
    restart: unless-stopped
    networks:
      - participes

volumes:
  composer_cache:
  public_dir:
  mysql:
  redis:

networks:
  participes:
    driver: bridge
